name: "Release Candidate Sign Off Action"
description: "Github Action to sign off a Release Candidate."
inputs:
  github-token:
    description: "Access token for your repository"
    required: true
  slack-webhook-url:
    description: "URL to send Slack webhooks to"
    required: true
runs:
  using: "node16"
  main: "index.js"
