name: "Release Candidate Sign Off Action"
description: "Creates a release tag, cleans up the release branch, and posts to a Slack webhook."
inputs:
  github-token:
    description: "Access token for your repository"
    required: true
runs:
  using: "node16"
  main: "index.js"
